server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/traveler_notification?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: travlerofficial2025@gmail.com
    password: qrbu xdzt imov rzpz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
    default-encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://traveler-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

whatsapp:
  api:
    url: https://graph.facebook.com/v22.0
  phone:
    number:
      id: 2425809414544405
  access:
    token: EAAMTtaoZCQ4sBQiLpzxwCNddAXIu3PzbhzPsJZC63uTnj1bQ91CCd2oVYUiYMDQzl4uqvGVzJvf94wKC3GGbbMs2bMzPxpZAsvdN8kCaWdZBWaf8Fe1DMQsIOYyjMLBOrXDPbhHhlBuOIz9gLqVHAVSjZCZAQPOUapD69e4UPg8fZCLhpozMJHAxihYWQd1IQZDZD

twilio:
  account:
    sid: ACd491f7c737d419707ca232960dea9a0c
  auth:
    token: 6852f8a3ad56065062788d8167cf0936
  whatsapp:
    number: whatsapp:+14155238886
