server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/traveler_notification?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: travlerofficial2025@gmail.com
    password: qrbu xdzt imov rzpz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
    default-encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://traveler-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

whatsapp:
  api:
    url: https://graph.facebook.com/v18.0
  phone:
    number:
      id: 941950635672547
  access:
    token: EAAVdnK4OwOkBQmHOuOz5Wh1ZCcMkB3hD31LT17WWUzuP2cPPKLrCwPPmbD1duSgGtLYxgqnVbJSYV6y2hKZCDARRAhtLoi25WcfUzpU01wRuGM51BUi5SrvPxgLK0Ge8noR2czmgmZBHMNZBLq1WoHIgEkkayJEXgbx7hU39ksqZABM4JyeKXiVSkfHmBLEgYxZAatDMJZB52OOab7jUVyXKw3PzjmZBanLV29TySxbWrDnP84xIbq4wU30kVABezcLnErZBt1ZACiUlrkEbkcVpvC

twilio:
  account:
    sid: ACd491f7c737d419707ca232960dea9a0c
  auth:
    token: 6852f8a3ad56065062788d8167cf0936
  whatsapp:
    number: whatsapp:+14155238886
