server:
  port: 8761

eureka:
  instance:
    hostname: traveler-discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://traveler-discovery:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics